2022-08-19 21:20:51,611 - root - INFO - ** Kedro project ames
2022-08-19 21:20:51,611 - root - INFO - Defined global variable `context`, `session`, `catalog` and `pipelines`
2022-08-19 21:20:53,454 - root - INFO - Registered line magic `run_viz`
2022-08-19 21:27:05,014 - kedro.framework.session.session - INFO - ** Kedro project page
2022-08-19 21:27:08,518 - kedro.io.data_catalog - INFO - Loading data from `alldata` (CSVDataSet)...
2022-08-19 21:27:08,519 - kedro.runner.sequential_runner - WARNING - There are 11 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:

2022-08-19 21:27:08,521 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
2022-08-19 21:30:27,733 - uvicorn.error - INFO - Started server process [57573]
2022-08-19 21:30:27,735 - uvicorn.error - INFO - Waiting for application startup.
2022-08-19 21:30:27,736 - uvicorn.error - INFO - Application startup complete.
2022-08-19 21:30:27,737 - uvicorn.error - INFO - Uvicorn running on http://127.0.0.1:4141 (Press CTRL+C to quit)
2022-08-19 21:30:57,186 - uvicorn.access - INFO - 127.0.0.1:59838 - "GET / HTTP/1.1" 200
2022-08-19 21:30:57,226 - uvicorn.access - INFO - 127.0.0.1:59838 - "GET /css/main.d78a5dc9.chunk.css HTTP/1.1" 200
2022-08-19 21:30:57,227 - uvicorn.access - INFO - 127.0.0.1:59840 - "GET /js/2.68614d35.chunk.js HTTP/1.1" 200
2022-08-19 21:30:57,228 - uvicorn.access - INFO - 127.0.0.1:59842 - "GET /js/main.eb019503.chunk.js HTTP/1.1" 200
2022-08-19 21:30:57,417 - uvicorn.error - INFO - ('127.0.0.1', 59844) - "WebSocket /graphql" [accepted]
2022-08-19 21:30:57,418 - uvicorn.error - INFO - connection open
2022-08-19 21:30:57,560 - uvicorn.access - INFO - 127.0.0.1:59840 - "GET /api/main HTTP/1.1" 200
2022-08-19 21:30:57,563 - kedro_viz.integrations.pypi - INFO - Checking for update...
2022-08-19 21:30:57,926 - uvicorn.access - INFO - 127.0.0.1:59842 - "POST /graphql HTTP/1.1" 200
2022-08-19 21:30:57,928 - uvicorn.access - INFO - 127.0.0.1:59840 - "GET /favicon.ico HTTP/1.1" 404
2022-08-19 21:31:00,725 - uvicorn.error - INFO - connection closed
2022-08-19 21:31:25,556 - uvicorn.error - INFO - Shutting down
2022-08-19 21:31:25,658 - uvicorn.error - INFO - Waiting for application shutdown.
2022-08-19 21:31:25,660 - uvicorn.error - INFO - Application shutdown complete.
2022-08-19 21:31:25,660 - uvicorn.error - INFO - Finished server process [57573]
2022-08-19 21:43:16,429 - kedro.framework.session.session - INFO - ** Kedro project page
2022-08-19 21:43:16,931 - kedro.io.data_catalog - INFO - Loading data from `alldata` (CSVDataSet)...
2022-08-19 21:43:16,958 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
2022-08-19 21:43:16,958 - kedro.pipeline.node - INFO - Running node: split_target_node_dev: split_target([alldata,parameters]) -> [X_dev,y_dev]
2022-08-19 21:43:16,960 - kedro.pipeline.node - ERROR - Node `split_target_node_dev: split_target([alldata,parameters]) -> [X_dev,y_dev]` failed with error: 
"['price'] not found in axis"
2022-08-19 21:43:16,961 - kedro.runner.sequential_runner - WARNING - There are 11 nodes that have not run.
You can resume the pipeline run by adding the following argument to your previous command:

2022-08-19 21:43:16,966 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
